### ISSUE TITLE
How to get the Talend runtime?

### ISSUE THREAD

**Issue by saitho** [tianqiwei/Talend-Runtime#1]
Hi,

thanks for your container.
I've been wondering where I can download the Talend Runtime ZIP package?
Is it not available for free?

Thanks.

**Comment by tianqi2407** [comment]
Hello,

It's a part of the package when you download the Talend Open Studio for data integration through their official website and it's a free version.

**Comment by saitho** [comment]
I downloaded Talend Open Studio for ESB. Couldn't find it there... neither on Data Integration.
Maybe it's different because I'm on MacOS.
It must be somewhere since I can run it locally via the IDE perfectly fine.
Can you tell me the path where you found it? :)

**Comment by saitho** [comment]
Nevermind, I found it...
The trick is not to download the Open Studio binary e.g. from https://www.talend.com/products/application-integration/esb-open-studio/. Instead download the ZIP archive which contains two folders "Studio" and "Runtime_ESBSE" from https://www.talend.com/products/application-integration/esb-manuals-release-notes/
